environment:
  # vars:
  language: android
  image: wasabeef/android
  # services:

build:
  # skip: false

#  before:
#    - echo "Building '${GIT_URL}' branch '${DOTCI_BRANCH}' commit '${DOTCI_SHA}'"

  # info:

  run:
    unit: ./gradlew lint
    # integration: 
    acceptance: ./gradlew connectedDebugTest

  # after:

notifications:
  - email:
    - sune.keller@gmail.com

plugins:
  artifacts: ./app/build/**/*.apk
